#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate the original OTHER REALM angular wordmark at native panel size.

Hand-drawn polygon letters inspired by the supplied Another World title style:
clipped corners, heavy black strokes, a narrow gold outline and extended
diagonals. These are original letter outlines (CC0), not extracted font data.
The 112x37 sprite is rasterized directly, with no resizing or antialiasing.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter
ROOT=Path(__file__).resolve().parents[1]
COLORS=[(0,0,0),(183,144,62),(8,12,20)]
# Each letter is an outer contour plus zero or more transparent counters.
GLYPHS={
 'O': ([(0,5),(5,0),(17,0),(17,11),(12,16),(0,16)],
       [[(4,6),(7,3),(13,3),(13,10),(10,13),(4,13)]]),
 'T': ([(0,0),(17,0),(17,4),(11,4),(11,16),(6,16),(6,4),(0,4)],[]),
 'H': ([(0,0),(4,0),(4,6),(13,6),(13,0),(17,0),(17,16),(13,16),(13,10),(4,10),(4,16),(0,16)],[]),
 'E': ([(0,0),(17,0),(17,4),(4,4),(4,6),(12,6),(12,10),(4,10),(4,12),(17,12),(17,16),(0,16)],[]),
 'R': ([(0,0),(17,0),(17,9),(12,9),(17,16),(11,16),(7,9),(4,9),(4,16),(0,16)],
       [[(4,3),(13,3),(13,6),(4,6)]]),
 'A': ([(0,16),(8,0),(17,0),(17,16),(13,16),(13,11),(7,8),(3,16)],
       [[(9,4),(13,4),(13,7),(8,5)]]),
 'L': ([(0,0),(4,0),(4,12),(17,12),(17,16),(0,16)],[]),
 'M': ([(0,16),(0,0),(4,0),(9,6),(14,0),(18,0),(18,16),(14,16),(14,7),(9,13),(4,7),(4,16)],[]),
}

def build():
    mask=Image.new('L',(112,37));draw=ImageDraw.Draw(mask)
    for text,y in [('OTHER',1),('REALM',19)]:
        for i,ch in enumerate(text):
            x=6+i*20;outer,holes=GLYPHS[ch]
            draw.polygon([(x+px,y+py) for px,py in outer],fill=255)
            for hole in holes:draw.polygon([(x+px,y+py) for px,py in hole],fill=0)
    # A short diagonal on the last M, echoing the reference's extended strokes.
    draw.polygon([(103,19),(110,35),(106,35),(100,22)],fill=255)
    outline=mask.filter(ImageFilter.MaxFilter(3))
    pixels=Image.new('P',mask.size)
    pixels.putpalette([v for c in COLORS for v in c]+[0]*(768-len(COLORS)*3))
    pixels.paste(1,(0,0),outline);pixels.paste(2,(0,0),mask)
    (ROOT/'assets').mkdir(exist_ok=True)
    pixels.save(ROOT/'assets/title.png',transparency=0)
    data=list(pixels.getdata());packed=[data[i]*16+data[i+1] for i in range(0,len(data),2)]
    palette=[((r>>3)<<11)|((g>>2)<<5)|(b>>3) for r,g,b in COLORS]
    header=['// Generated by tools/title_art.py; original CC0 polygon lettering.',
            '#pragma once','#include <stdint.h>','namespace otherrealm {',
            f'enum {{TitleWidth={pixels.width},TitleHeight={pixels.height},TitleTop=3}};',
            'static const uint16_t titlePalette[]={'+','.join(hex(c) for c in palette)+'};',
            'static const uint8_t titleSprite[]={']
    header+=['    '+','.join(f'0x{b:02x}' for b in packed[i:i+24])+',' for i in range(0,len(packed),24)]
    header+=['};','}','']
    (ROOT/'engine/aw_title_art.h').write_text('\n'.join(header),encoding='ascii')
    print('Native title sprite:',pixels.size,len(packed),'bytes')

if __name__=='__main__':build()
