#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Extract unscaled uppercase menu glyphs from PixelLogoLab's public-domain BDFs.

The generated header is checked in; building Otherrealm does not need the font
collection, Pillow or a runtime font loader. No font pixels are resized.
"""
import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read_font(path):
    text = path.read_text(encoding="ascii")
    lines = text.splitlines()
    box = next(tuple(map(int, line.split()[1:])) for line in lines if line.startswith("FONTBOUNDINGBOX "))
    width, height, xoff, yoff = box
    if width > 8 or xoff or 'COPYRIGHT "Public domain' not in text:
        raise ValueError(f"Expected a public-domain fixed-width font: {path}")
    glyphs = {}
    for block in text.split("STARTCHAR ")[1:]:
        part = block.split("ENDCHAR", 1)[0].splitlines()
        code = int(next(line.split()[1] for line in part if line.startswith("ENCODING ")))
        if not 32 <= code <= 95:
            continue
        advance = next(tuple(map(int, line.split()[1:])) for line in part if line.startswith("DWIDTH "))
        bounds = next(tuple(map(int, line.split()[1:])) for line in part if line.startswith("BBX "))
        if advance != (width, 0) or bounds != box:
            raise ValueError(f"Unexpected glyph metrics: {path}, character {code}")
        rows = [int(row, 16) for row in part[part.index("BITMAP") + 1:] if row.strip()]
        if len(rows) != height or any(row >= 256 for row in rows):
            raise ValueError("Unexpected bitmap row")
        glyphs[code] = rows
    if len(glyphs) != 64:
        raise ValueError("Incomplete menu character range")
    return width, height, glyphs


def generate(directory, destination):
    out = ["// Generated by tools/vendor_ui_fonts.py; do not edit glyph data.",
           "// Public-domain X11 Misc Fixed fonts, from PixelLogoLab/fonts/u8g2.",
           '// Source notice: "Public domain font.  Share and enjoy."',
           "// 8x13 Bold for headings/items; 5x8 Regular for small status lines.",
           "// Every source bitmap pixel maps to one display pixel (no scaling).",
           "#pragma once", "#include <stdint.h>", "namespace otherrealm {"]
    for filename, name in (("8x13B.bdf", "Menu"), ("5x8.bdf", "Status")):
        path = directory / filename
        width, height, glyphs = read_font(path)
        out += [f"// {filename} SHA256 {hashlib.sha256(path.read_bytes()).hexdigest()}",
                f"enum {{ Ui{name}Width={width}, Ui{name}Height={height} }};",
                f"static const uint8_t ui{name}Glyphs[64][{height}]={{"]
        for code in range(32, 96):
            out.append("    {" + ",".join(f"0x{r:02x}" for r in glyphs[code]) + f"}}, // ASCII {code}")
        out += ["};"]
    out += ["inline uint8_t uiFontRow(uint8_t ch,uint8_t row,bool small){",
            "    if(ch>='a'&&ch<='z')ch-=32;",
            "    if(ch<32||ch>95)return 0;",
            "    return small?(row<UiStatusHeight?uiStatusGlyphs[ch-32][row]:0):",
            "                 (row<UiMenuHeight?uiMenuGlyphs[ch-32][row]:0);",
            "}", "}", ""]
    destination.write_text("\n".join(out), encoding="ascii")
    print(f"Wrote {destination}: 1,344 font bytes in flash, no extra RAM")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fonts", type=Path, default=Path("D:/LocalProjects/PixelLogoLab/fonts/u8g2"))
    parser.add_argument("--output", type=Path, default=ROOT / "engine/aw_ui_font.h")
    args = parser.parse_args()
    generate(args.fonts, args.output)
